-- Script para Supabase (PostgreSQL)
-- Compatible con el backend en back/controllers/controllers.js

begin;

-- 1) Tabla de usuarios
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  role text not null default 'cliente',
  email text not null unique,
  password text not null,
  phone text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_users_email on public.users (email);

-- 2) Tabla de productos
create table if not exists public.producto (
  id bigint generated by default as identity primary key,
  nombre_producto text not null,
  descripcion_producto text,
  stock_disponible integer not null default 0 check (stock_disponible >= 0),
  tipo text,
  color text,
  precio numeric(12,2) not null check (precio > 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_producto_nombre on public.producto (nombre_producto);

-- 3) Tabla de imagenes de productos
create table if not exists public.imagen_producto (
  id_imagen bigint generated by default as identity primary key,
  ruta_imagen text not null,
  nombre_imagen text not null,
  codigo_producto bigint not null,
  created_at timestamptz not null default now(),
  constraint fk_imagen_producto_producto
    foreign key (codigo_producto)
    references public.producto(id)
    on delete cascade
);

create index if not exists idx_imagen_producto_codigo_producto
  on public.imagen_producto (codigo_producto);

-- 4) Tabla de comentarios
create table if not exists public.comentario (
  id_comentario bigint generated by default as identity primary key,
  codigo_cliente bigint not null,
  codigo_producto bigint not null,
  texto text not null,
  fecha_creacion timestamptz not null default now(),
  constraint fk_comentario_users
    foreign key (codigo_cliente)
    references public.users(id)
    on delete cascade,
  constraint fk_comentario_producto
    foreign key (codigo_producto)
    references public.producto(id)
    on delete cascade
);

create index if not exists idx_comentario_codigo_producto
  on public.comentario (codigo_producto);
create index if not exists idx_comentario_codigo_cliente
  on public.comentario (codigo_cliente);

commit;

-- ==========================================
-- RLS / permisos para que funcione rapido
-- ==========================================
-- Si usas SUPABASE_API_KEY con service_role en el backend,
-- no necesitas abrir politicas para anon.
-- Si estas usando anon key en tu backend, descomenta este bloque.

-- alter table public.users enable row level security;
-- alter table public.producto enable row level security;
-- alter table public.imagen_producto enable row level security;
-- alter table public.comentario enable row level security;

-- create policy "users_all" on public.users
--   for all to anon, authenticated
--   using (true) with check (true);

-- create policy "producto_all" on public.producto
--   for all to anon, authenticated
--   using (true) with check (true);

-- create policy "imagen_producto_all" on public.imagen_producto
--   for all to anon, authenticated
--   using (true) with check (true);

-- create policy "comentario_all" on public.comentario
--   for all to anon, authenticated
--   using (true) with check (true);
